language: node_js
node_js:
- '10'
services:
- docker
deploy:
  provider: npm
  email: "benzaita@gmail.com"
  api_key:
    secure: AJHDBWO38zYptInjivYWITp5hy3kMCwNrkb+Grh1Y4DnFZW0jQzbWI2cWQzYZxus2/Sw8GTiDUc+AofkhYT2nXtGAYot2uMm48HRY3QMqEnzThIrKS9udmgqLgFYuRXdCxUI1aXogtrmb5RJVHkktHtoSz6gNlx+xCvvCKaWsMRJlQyvmxa7j88MsP9C61EoDQXJlAy3Zf0rwWZ/JfRWXdYmR8c8FZSirvhu8qWjs0uDOSPeWCNiGGDaec0IyeqrLx0wc/PPP5UBxizCT8sC9w7zaRrivUrqcM/cl8omkWqYs6MHPT7jdDHZweu9nb5TSjRu6NBtcn2rWIUz0pI913LaAEcl3ObFXPrXpyYcMIhdlMeoT9MJ2t5wp0BC32kkbSunOWfigamECavv83A99Mf7lyrpbwgSQ4xmdcha9NVkZ0CoRGLGumG0py4jiSVUc+yNFkkUkIv2j00sCMwmTNX5tY1phsuYAUozzdvriqBfHg3t7XX4jWaswDBAxDsW8O+32q/JVvYqN3QOBnTzMgG/9eqjkJ0ySHhRoMSGP/HF3PDDVrDnBeg2OOxxZ6fBUtnQaaiRo8sNzt9J4E0JNWpT/hsdNIQo9hyX7uhtmW/lnOaMOW15ws3NC2PPXt6WIPJtNtY04VsZfoJIC0NCEHRjeIOxGH+LSlVVrqg6kro=
  on:
    branch: master
