site_name: dockerized
site_url: https://benzaita.github.io/dockerized-cli/
repo_url: https://github.com/benzaita/dockerized-cli/
edit_uri: edit/docs/docs/

nav:
    - Home: index.md
    - Tutorials:
        - 'Quick Start': tutorials/quick_start.md
    - 'How-To Guides':
        - 'Provide AWS Credentials': how_to_guides/provide_aws_credentials.md
        - 'Pass Environment Variables': how_to_guides/pass_environment_variables.md
        - 'Cache the "dockerized" Docker image': how_to_guides/cache_the_dockerized_docker_image.md
        - 'Utilize Package-Managers Cache': how_to_guides/utilize_package_managers_cache.md
        - 'Use with VSCode Remote Containers': how_to_guides/use_with_vscode_remote_containers.md
    - Explanations:
        - 'How "dockerized exec" works': explanations/how_dockerized_exec_works.md
        - 'Why use dockerized': explanations/why_use_dockerized.md
    - Reference:
        - 'Starter Kits': reference/starter_kits.md

theme:
  name: material
  custom_dir: overrides

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

# TODO enable when mkdocs-material version >7.1.7 is available and also `mv overrides/partials/integrations/analytics.html overrides/partials/integrations/analytics/microanalytics.html`
# extra:
#   analytics:
#     provider: microanalytics

google_analytics:
   - dummy
   - auto