version: '2'
services:
  dockerized:
    build:
      context: .
      dockerfile: Dockerfile.dockerized
    entrypoint:
      - sh
      - '-c'
    environment: []
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: library/redis:4-alpine3.8

volumes: {}
