version: '2'
services:
  cenv:
    build:
      context: .
      dockerfile: Dockerfile.cenv
    entrypoint:
      - sh
      - '-c'
    environment: []
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: host
volumes: {}
